"""Textured building maquettes: licensed photos -> TRELLIS (on the pod, trellis_worker.py) -> GLB -> data/models3d.

    python backend/tools/buildings3d.py upload            # crops + photos to the pod (job /workspace/b3d_job/<slug>/<variant>/)
    python backend/tools/buildings3d.py run 1,2,3         # start the worker for those seeds (log: /workspace/b3d_run.log)
    python backend/tools/buildings3d.py fetch             # pull every candidate to data/models3d/_cand/ and render comparisons
    python backend/tools/buildings3d.py finalize thal A_s1 [--ref 02.jpg]   # recompress, copy, attribution, README

Slugs: thal=jamia-masjid-thal, palace=white-palace-marghazar, museum=swat-museum. Variant A = best single photo, B = multi-image.
"""
import io
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import httpx
import trimesh
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
import pod_files  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PHOTOS, OUT, JOB = ROOT / "data" / "photos", ROOT / "data" / "models3d", "/workspace/b3d_job"
BLENDER = "D:/TinyAtlas/tools/blender-5.2.2-windows-x64/blender.exe"
SLUG = {"thal": "jamia-masjid-thal", "palace": "white-palace-marghazar", "museum": "swat-museum"}
# name -> (source photo, crop box); crops drop cars, people, lawn furniture where a simple crop can
CROPS = {"thal_02": ("jamia-masjid-thal/02.jpg", (260, 0, 1800, 1010)), "thal_01": ("jamia-masjid-thal/01.jpg", (0, 0, 960, 610)),
         "palace_05": ("white-palace-marghazar/05.jpg", (0, 190, 1920, 960)), "palace_02": ("white-palace-marghazar/02.jpg", (0, 0, 1296, 700)),
         "palace_14": ("white-palace-marghazar/14.jpg", (0, 250, 1920, 1250)), "museum_04": ("swat-museum/04.jpg", (0, 0, 1920, 1250)),
         "museum_05": ("swat-museum/05.jpg", (0, 0, 720, 420))}
VARIANTS = {"thal": {"A": ["thal_02"], "B": ["thal_02", "thal_01"]},
            "palace": {"A": ["palace_05"], "B": ["palace_02", "palace_14", "palace_05"]},
            "museum": {"A": ["museum_05"], "B": ["museum_04"]}}
MODEL = "3D shape generated by TRELLIS (Microsoft, MIT licence)"


def pod(cmd: str) -> str:
    return subprocess.run([sys.executable, str(Path(__file__).resolve().parent / "pod_run.py"), cmd], capture_output=True, text=True).stdout


def upload() -> None:
    with httpx.Client() as c:
        for slug, vs in VARIANTS.items():
            for v, names in vs.items():
                pod_files.mkdir(f"{JOB}/{slug}/{v}", c)
                for n in names:
                    src, box = CROPS[n]
                    buf = io.BytesIO()
                    Image.open(PHOTOS / src).convert("RGB").crop(box).save(buf, "PNG")
                    tmp = OUT / "_cand" / f"{n}.png"
                    tmp.parent.mkdir(parents=True, exist_ok=True)
                    tmp.write_bytes(buf.getvalue())
                    pod_files.put(tmp, f"{JOB}/{slug}/{v}/{n}.png", c)


def fetch() -> None:
    cand = OUT / "_cand"
    cand.mkdir(parents=True, exist_ok=True)
    for line in sorted(set(re.findall(rf"{JOB}/\w+/\w+\.glb", pod(f"ls {JOB}/*/*.glb")))):
        if True:
            slug, name = line.split("/")[-2:]
            local = cand / f"{slug}_{name}"
            if not local.exists():
                pod_files.get(line, local)
            if not (cand / f"{local.stem}_a.png").exists():
                subprocess.run([BLENDER, "-b", "-P", str(Path(__file__).resolve().parent / "blender" / "glb_compare.py"), "--",
                                str(local), str(cand / local.stem)], capture_output=True)
            print(local.name, f"{local.stat().st_size / 1e6:.2f} MB")


def finalize(slug: str, cand: str, ref: str) -> None:
    full = SLUG[slug]
    scene = trimesh.load(OUT / "_cand" / f"{slug}_{cand}.glb")
    mesh = next(iter(scene.geometry.values())) if hasattr(scene, "geometry") else scene
    mat = mesh.visual.material
    tex = getattr(mat, "baseColorTexture", None) or getattr(mat, "image", None)
    if tex is not None:                      # PNG 1024^2 is ~1.5 MB; JPEG keeps the GLB small
        buf = io.BytesIO()
        tex.convert("RGB").save(buf, "JPEG", quality=85)
        mat.baseColorTexture = Image.open(io.BytesIO(buf.getvalue()))
    mesh.export(OUT / f"{full}.glb")
    manifest = json.loads((PHOTOS / full / "manifest.json").read_text(encoding="utf-8"))
    lines = [f"{full}.glb", MODEL, "Source photos:"]
    for p in manifest["photos"]:
        lines.append(f"- {p['file']}: {p['attribution']} ({p['licence']}) {p['page']}")
    (OUT / f"{full}.attribution.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(full, len(mesh.faces), "tris", f"{(OUT / f'{full}.glb').stat().st_size / 1e6:.2f} MB")


if __name__ == "__main__":
    op = sys.argv[1]
    if op == "upload":
        upload()
    elif op == "run":
        pod(f"cd /workspace && SEEDS={sys.argv[2]} setsid nohup /workspace/trellis/bin/python /workspace/trellis_worker.py {JOB} "
            "> /workspace/b3d_run.log 2>&1 < /dev/null & disown")
    elif op == "fetch":
        fetch()
    elif op == "finalize":
        finalize(sys.argv[2], sys.argv[3], "")
